language: java
deploy:
  provider: releases
  api_key:
    secure: Ay9yKZQk/Enf9bwfbEJDJcVBwZht4df1xrbMVrjJhSCcGkjzHRmBj9RiQKZ4eWsZYd1Kk7bS5LSFT2/VAylN4153ai+TCfZASmQGESVG/cMEZ9XrfEvX6MlqIxPwBz3CO8EJNTj9LgDa2xXC1cTbUYVQVaGzw5fDO35m/yaI+r0LN8Y8vtKsXVU1xnA2xrtfIOyE01dt31WqzvYOzdQJXG/XKiMf+Me095a9Fkl8BEia5sWKA9+G1DWagRLwk3zADDaFXIIxnfN1hfWoDQ8WX51QGmolDS382ThnP0OZCsFXGOUBFM0J5X5ByovfDAr+jbfaHXOKQIbXKrKfx/dUgYhNQS7IDAMk49deGZUa++VNPfZYT62Qvrdyxy1UbrGNYEPTtTjTyCTpuHrUJowQQz2gwD3djgqO5mBGW8mP+FXbcY1h/gnp7retSdTToRnGy5HdeyWOI0TVPAYzZS6vzF8Jg9rSExaMpr9nP/FmZuHRV52+zAElJ3eeG2OeLQqeofHOnbd9ZyaALmZRd4VvZDE9/ks7fJw6fodE0P5VqS6Yw6z4WbbHyK4i6seNRN0tobPb6znAubjQTmXSAYkh2FJDEkUEAMf+shw5vAE2b22WrHF7Fsq3mNB9j9srLeADyeSkW7EO3CAdOy/oYxGK9JY3mowjKWzpJSgM0j5FO18=
  file_glob: true
  file: "build/libs/xlr-apigee-test-plugin-*.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xlr-apigee-test-plugin
